
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'mainNUMBER ID OPBIN LP RP LB RB EQUAL SEQ COMMA INT FLOAT PRINT WHILE MAIN RETURNexpression : NUMBER\n                | ID\n                | expression OPBIN expressioncommande : ID EQUAL expression\n                | commande SEQ commande\n                | WHILE LP expression RP LB commande RB\n    \n    declaration : INT ID\n                | FLOAT ID\n    \n    listedeclarations : declaration SEQ\n                      | declaration SEQ listedeclarations\n    \n    listevariables : ID\n                   | ID COMMA listevariables\n    \n    main : MAIN LP listevariables RP LB listedeclarations commande SEQ PRINT LP expression RP SEQ RB\n    '
    
_lr_action_items = {'RP':([4,5,9,24,25,26,35,36,],[6,-11,-12,-1,30,-2,-3,38,]),'RB':([24,26,27,29,35,37,39,40,],[-1,-2,-5,-4,-3,39,-6,41,]),'SEQ':([13,15,17,18,24,26,27,29,35,37,38,39,],[19,21,-7,-8,-1,-2,32,-4,-3,32,40,-6,]),'INT':([8,19,],[11,11,]),'OPBIN':([24,25,26,29,35,36,],[-1,31,-2,31,31,31,]),'FLOAT':([8,19,],[12,12,]),'EQUAL':([16,],[22,]),'NUMBER':([20,22,31,33,],[24,24,24,24,]),'WHILE':([10,19,21,23,32,34,],[14,-9,14,-10,14,14,]),'COMMA':([5,],[7,]),'LP':([1,14,28,],[3,20,33,]),'PRINT':([21,],[28,]),'LB':([6,30,],[8,34,]),'MAIN':([0,],[1,]),'ID':([3,7,10,11,12,19,20,21,22,23,31,32,33,34,],[5,5,16,17,18,-9,26,16,26,-10,26,16,26,16,]),'$end':([2,41,],[0,-13,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'listedeclarations':([8,19,],[10,23,]),'listevariables':([3,7,],[4,9,]),'commande':([10,21,32,34,],[15,27,27,37,]),'declaration':([8,19,],[13,13,]),'main':([0,],[2,]),'expression':([20,22,31,33,],[25,29,35,36,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> main","S'",1,None,None,None),
  ('expression -> NUMBER','expression',1,'p_expression','compilateur.py',67),
  ('expression -> ID','expression',1,'p_expression','compilateur.py',68),
  ('expression -> expression OPBIN expression','expression',3,'p_expression','compilateur.py',69),
  ('commande -> ID EQUAL expression','commande',3,'p_commande','compilateur.py',79),
  ('commande -> commande SEQ commande','commande',3,'p_commande','compilateur.py',80),
  ('commande -> WHILE LP expression RP LB commande RB','commande',7,'p_commande','compilateur.py',81),
  ('declaration -> INT ID','declaration',2,'p_declaration','compilateur.py',96),
  ('declaration -> FLOAT ID','declaration',2,'p_declaration','compilateur.py',97),
  ('listedeclarations -> declaration SEQ','listedeclarations',2,'p_listedeclarations','compilateur.py',111),
  ('listedeclarations -> declaration SEQ listedeclarations','listedeclarations',3,'p_listedeclarations','compilateur.py',112),
  ('listevariables -> ID','listevariables',1,'p_listevariables','compilateur.py',132),
  ('listevariables -> ID COMMA listevariables','listevariables',3,'p_listevariables','compilateur.py',133),
  ('main -> MAIN LP listevariables RP LB listedeclarations commande SEQ PRINT LP expression RP SEQ RB','main',14,'p_main','compilateur.py',143),
]
